# Generated by Django 3.2.9 on 2024-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default=11, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
